var data={"Stores":[
					{
						"name":"优品阁",
						"introduce":"这里是店铺介绍",
						"browseNum":"666",
						"imageUrl":"../img/store-1.jpg",
						"imgList":[
							{
								"url":"../img/list-1.jpg",
								"info":{
									"goodsName":"猫咪杯子情侣动物水杯可爱创意陶瓷马克杯咖啡生日礼物带杯盖勺子 ",
									"goodsPrice":"20.00",
									"goodsDetail":""
								}
							},
							{
								"url":"../img/list-2.jpg",
								"info":{
									"goodsName":"情侣网红花生鼠公仔生日送小礼物男女生创意儿童毛绒玩具六一礼物 ",
									"goodsPrice":"25.40",
									"goodsDetail":""
								}
							},
							{
								"url":"../img/list-3.jpg",
								"info":{
									"goodsName":"车饰车载摆设车内用品汽车子饰品摆件小物件个性创意可爱小工艺品",
									"goodsPrice":"14.80",
									"goodsDetail":""
								}
							},
							{
								"url":"../img/list-4.jpg",
								"info":{
									"goodsName":"OFF-WHITE 印花T恤",
									"goodsPrice":"48.80",
									"goodsDetail":""
								}
							},
							{
								"url":"../img/list-5.jpg",
								"info":{
									"goodsName":"小马可爱树脂摆件设客厅居家装饰品北欧风格创意工艺品桌面礼物品",
									"goodsPrice":"27.30",
									"goodsDetail":""
								}
							}
						],
					},
					{
						"name":"矿大一号店",
						"introduce":"这里是店铺介绍",
						"browseNum":"666",
						"imageUrl":"../img/store-2.png",
						"imgList":[
							{
								"url":"../img/list-1.jpg",
								"info":{
									"goodsName":"猫咪杯子情侣动物水杯可爱创意陶瓷马克杯咖啡生日礼物带杯盖勺子 ",
									"goodsPrice":"20.00",
									"goodsDetail":""
								}
							},
							{
								"url":"../img/list-2.jpg",
								"info":{
									"goodsName":"情侣网红花生鼠公仔生日送小礼物男女生创意儿童毛绒玩具六一礼物 ",
									"goodsPrice":"25.40",
									"goodsDetail":""
								}
							},
							{
								"url":"../img/list-3.jpg",
								"info":{
									"goodsName":"车饰车载摆设车内用品汽车子饰品摆件小物件个性创意可爱小工艺品",
									"goodsPrice":"14.80",
									"goodsDetail":""
								}
							},
							{
								"url":"../img/list-4.jpg",
								"info":{
									"goodsName":"OFF-WHITE 印花T恤",
									"goodsPrice":"48.80",
									"goodsDetail":""
								}
							},
							{
								"url":"../img/list-5.jpg",
								"info":{
									"goodsName":"小马可爱树脂摆件设客厅居家装饰品北欧风格创意工艺品桌面礼物品",
									"goodsPrice":"27.30",
									"goodsDetail":""
								}
							}
						],
					},
					{
						"name":"矿大一号店",
						"introduce":"这里是店铺介绍",
						"browseNum":"666",
						"imageUrl":"../img/store-2.png",
						"imgList":[
							{
								"url":"../img/list-1.jpg",
								"info":{
									"goodsName":"猫咪杯子情侣动物水杯可爱创意陶瓷马克杯咖啡生日礼物带杯盖勺子 ",
									"goodsPrice":"20.00",
									"goodsDetail":""
								}
							},
							{
								"url":"../img/list-2.jpg",
								"info":{
									"goodsName":"情侣网红花生鼠公仔生日送小礼物男女生创意儿童毛绒玩具六一礼物 ",
									"goodsPrice":"25.40",
									"goodsDetail":""
								}
							},
							{
								"url":"../img/list-3.jpg",
								"info":{
									"goodsName":"车饰车载摆设车内用品汽车子饰品摆件小物件个性创意可爱小工艺品",
									"goodsPrice":"14.80",
									"goodsDetail":""
								}
							},
							{
								"url":"../img/list-4.jpg",
								"info":{
									"goodsName":"OFF-WHITE 印花T恤",
									"goodsPrice":"48.80",
									"goodsDetail":""
								}
							},
							{
								"url":"../img/list-5.jpg",
								"info":{
									"goodsName":"小马可爱树脂摆件设客厅居家装饰品北欧风格创意工艺品桌面礼物品",
									"goodsPrice":"27.30",
									"goodsDetail":""
								}
							}
						],
					},
	{
						"name":"优品阁",
						"introduce":"这里是店铺介绍",
						"browseNum":"666",
						"imageUrl":"../img/store-1.jpg",
						"imgList":[
							{
								"url":"../img/list-1.jpg",
								"info":{
									"goodsName":"猫咪杯子情侣动物水杯可爱创意陶瓷马克杯咖啡生日礼物带杯盖勺子 ",
									"goodsPrice":"20.00",
									"goodsDetail":""
								}
							},
							{
								"url":"../img/list-2.jpg",
								"info":{
									"goodsName":"情侣网红花生鼠公仔生日送小礼物男女生创意儿童毛绒玩具六一礼物 ",
									"goodsPrice":"25.40",
									"goodsDetail":""
								}
							},
							{
								"url":"../img/list-3.jpg",
								"info":{
									"goodsName":"车饰车载摆设车内用品汽车子饰品摆件小物件个性创意可爱小工艺品",
									"goodsPrice":"14.80",
									"goodsDetail":""
								}
							},
							{
								"url":"../img/list-4.jpg",
								"info":{
									"goodsName":"OFF-WHITE 印花T恤",
									"goodsPrice":"48.80",
									"goodsDetail":""
								}
							},
							{
								"url":"../img/list-5.jpg",
								"info":{
									"goodsName":"小马可爱树脂摆件设客厅居家装饰品北欧风格创意工艺品桌面礼物品",
									"goodsPrice":"27.30",
									"goodsDetail":""
								}
							}
						],
					},
	{
						"name":"优品阁",
						"introduce":"这里是店铺介绍",
						"browseNum":"666",
						"imageUrl":"../img/store-1.jpg",
						"imgList":[
							{
								"url":"../img/list-1.jpg",
								"info":{
									"goodsName":"猫咪杯子情侣动物水杯可爱创意陶瓷马克杯咖啡生日礼物带杯盖勺子 ",
									"goodsPrice":"20.00",
									"goodsDetail":""
								}
							},
							{
								"url":"../img/list-2.jpg",
								"info":{
									"goodsName":"情侣网红花生鼠公仔生日送小礼物男女生创意儿童毛绒玩具六一礼物 ",
									"goodsPrice":"25.40",
									"goodsDetail":""
								}
							},
							{
								"url":"../img/list-3.jpg",
								"info":{
									"goodsName":"车饰车载摆设车内用品汽车子饰品摆件小物件个性创意可爱小工艺品",
									"goodsPrice":"14.80",
									"goodsDetail":""
								}
							},
							{
								"url":"../img/list-4.jpg",
								"info":{
									"goodsName":"OFF-WHITE 印花T恤",
									"goodsPrice":"48.80",
									"goodsDetail":""
								}
							},
							{
								"url":"../img/list-5.jpg",
								"info":{
									"goodsName":"小马可爱树脂摆件设客厅居家装饰品北欧风格创意工艺品桌面礼物品",
									"goodsPrice":"27.30",
									"goodsDetail":""
								}
							}
						],
					},
	{
						"name":"优品阁",
						"introduce":"这里是店铺介绍",
						"browseNum":"666",
						"imageUrl":"../img/store-1.jpg",
						"imgList":[
							{
								"url":"../img/list-1.jpg",
								"info":{
									"goodsName":"猫咪杯子情侣动物水杯可爱创意陶瓷马克杯咖啡生日礼物带杯盖勺子 ",
									"goodsPrice":"20.00",
									"goodsDetail":""
								}
							},
							{
								"url":"../img/list-2.jpg",
								"info":{
									"goodsName":"情侣网红花生鼠公仔生日送小礼物男女生创意儿童毛绒玩具六一礼物 ",
									"goodsPrice":"25.40",
									"goodsDetail":""
								}
							},
							{
								"url":"../img/list-3.jpg",
								"info":{
									"goodsName":"车饰车载摆设车内用品汽车子饰品摆件小物件个性创意可爱小工艺品",
									"goodsPrice":"14.80",
									"goodsDetail":""
								}
							},
							{
								"url":"../img/list-4.jpg",
								"info":{
									"goodsName":"OFF-WHITE 印花T恤",
									"goodsPrice":"48.80",
									"goodsDetail":""
								}
							},
							{
								"url":"../img/list-5.jpg",
								"info":{
									"goodsName":"小马可爱树脂摆件设客厅居家装饰品北欧风格创意工艺品桌面礼物品",
									"goodsPrice":"27.30",
									"goodsDetail":""
								}
							}
						],
					},
	{
						"name":"优品阁",
						"introduce":"这里是店铺介绍",
						"browseNum":"666",
						"imageUrl":"../img/store-1.jpg",
						"imgList":[
							{
								"url":"../img/list-1.jpg",
								"info":{
									"goodsName":"猫咪杯子情侣动物水杯可爱创意陶瓷马克杯咖啡生日礼物带杯盖勺子 ",
									"goodsPrice":"20.00",
									"goodsDetail":""
								}
							},
							{
								"url":"../img/list-2.jpg",
								"info":{
									"goodsName":"情侣网红花生鼠公仔生日送小礼物男女生创意儿童毛绒玩具六一礼物 ",
									"goodsPrice":"25.40",
									"goodsDetail":""
								}
							},
							{
								"url":"../img/list-3.jpg",
								"info":{
									"goodsName":"车饰车载摆设车内用品汽车子饰品摆件小物件个性创意可爱小工艺品",
									"goodsPrice":"14.80",
									"goodsDetail":""
								}
							},
							{
								"url":"../img/list-4.jpg",
								"info":{
									"goodsName":"OFF-WHITE 印花T恤",
									"goodsPrice":"48.80",
									"goodsDetail":""
								}
							},
							{
								"url":"../img/list-5.jpg",
								"info":{
									"goodsName":"小马可爱树脂摆件设客厅居家装饰品北欧风格创意工艺品桌面礼物品",
									"goodsPrice":"27.30",
									"goodsDetail":""
								}
							}
						],
					},
	{
						"name":"优品阁",
						"introduce":"这里是店铺介绍",
						"browseNum":"666",
						"imageUrl":"../img/store-1.jpg",
						"imgList":[
							{
								"url":"../img/list-1.jpg",
								"info":{
									"goodsName":"猫咪杯子情侣动物水杯可爱创意陶瓷马克杯咖啡生日礼物带杯盖勺子 ",
									"goodsPrice":"20.00",
									"goodsDetail":""
								}
							},
							{
								"url":"../img/list-2.jpg",
								"info":{
									"goodsName":"情侣网红花生鼠公仔生日送小礼物男女生创意儿童毛绒玩具六一礼物 ",
									"goodsPrice":"25.40",
									"goodsDetail":""
								}
							},
							{
								"url":"../img/list-3.jpg",
								"info":{
									"goodsName":"车饰车载摆设车内用品汽车子饰品摆件小物件个性创意可爱小工艺品",
									"goodsPrice":"14.80",
									"goodsDetail":""
								}
							},
							{
								"url":"../img/list-4.jpg",
								"info":{
									"goodsName":"OFF-WHITE 印花T恤",
									"goodsPrice":"48.80",
									"goodsDetail":""
								}
							},
							{
								"url":"../img/list-5.jpg",
								"info":{
									"goodsName":"小马可爱树脂摆件设客厅居家装饰品北欧风格创意工艺品桌面礼物品",
									"goodsPrice":"27.30",
									"goodsDetail":""
								}
							}
						],
					},
	{
						"name":"优品阁",
						"introduce":"这里是店铺介绍",
						"browseNum":"666",
						"imageUrl":"../img/store-1.jpg",
						"imgList":[
							{
								"url":"../img/list-1.jpg",
								"info":{
									"goodsName":"猫咪杯子情侣动物水杯可爱创意陶瓷马克杯咖啡生日礼物带杯盖勺子 ",
									"goodsPrice":"20.00",
									"goodsDetail":""
								}
							},
							{
								"url":"../img/list-2.jpg",
								"info":{
									"goodsName":"情侣网红花生鼠公仔生日送小礼物男女生创意儿童毛绒玩具六一礼物 ",
									"goodsPrice":"25.40",
									"goodsDetail":""
								}
							},
							{
								"url":"../img/list-3.jpg",
								"info":{
									"goodsName":"车饰车载摆设车内用品汽车子饰品摆件小物件个性创意可爱小工艺品",
									"goodsPrice":"14.80",
									"goodsDetail":""
								}
							},
							{
								"url":"../img/list-4.jpg",
								"info":{
									"goodsName":"OFF-WHITE 印花T恤",
									"goodsPrice":"48.80",
									"goodsDetail":""
								}
							},
							{
								"url":"../img/list-5.jpg",
								"info":{
									"goodsName":"小马可爱树脂摆件设客厅居家装饰品北欧风格创意工艺品桌面礼物品",
									"goodsPrice":"27.30",
									"goodsDetail":""
								}
							}
						],
					},
	{
						"name":"优品阁",
						"introduce":"这里是店铺介绍",
						"browseNum":"666",
						"imageUrl":"../img/store-1.jpg",
						"imgList":[
							{
								"url":"../img/list-1.jpg",
								"info":{
									"goodsName":"猫咪杯子情侣动物水杯可爱创意陶瓷马克杯咖啡生日礼物带杯盖勺子 ",
									"goodsPrice":"20.00",
									"goodsDetail":""
								}
							},
							{
								"url":"../img/list-2.jpg",
								"info":{
									"goodsName":"情侣网红花生鼠公仔生日送小礼物男女生创意儿童毛绒玩具六一礼物 ",
									"goodsPrice":"25.40",
									"goodsDetail":""
								}
							},
							{
								"url":"../img/list-3.jpg",
								"info":{
									"goodsName":"车饰车载摆设车内用品汽车子饰品摆件小物件个性创意可爱小工艺品",
									"goodsPrice":"14.80",
									"goodsDetail":""
								}
							},
							{
								"url":"../img/list-4.jpg",
								"info":{
									"goodsName":"OFF-WHITE 印花T恤",
									"goodsPrice":"48.80",
									"goodsDetail":""
								}
							},
							{
								"url":"../img/list-5.jpg",
								"info":{
									"goodsName":"小马可爱树脂摆件设客厅居家装饰品北欧风格创意工艺品桌面礼物品",
									"goodsPrice":"27.30",
									"goodsDetail":""
								}
							}
						],
					},
	{
						"name":"优品阁",
						"introduce":"这里是店铺介绍",
						"browseNum":"666",
						"imageUrl":"../img/store-1.jpg",
						"imgList":[
							{
								"url":"../img/list-1.jpg",
								"info":{
									"goodsName":"猫咪杯子情侣动物水杯可爱创意陶瓷马克杯咖啡生日礼物带杯盖勺子 ",
									"goodsPrice":"20.00",
									"goodsDetail":""
								}
							},
							{
								"url":"../img/list-2.jpg",
								"info":{
									"goodsName":"情侣网红花生鼠公仔生日送小礼物男女生创意儿童毛绒玩具六一礼物 ",
									"goodsPrice":"25.40",
									"goodsDetail":""
								}
							},
							{
								"url":"../img/list-3.jpg",
								"info":{
									"goodsName":"车饰车载摆设车内用品汽车子饰品摆件小物件个性创意可爱小工艺品",
									"goodsPrice":"14.80",
									"goodsDetail":""
								}
							},
							{
								"url":"../img/list-4.jpg",
								"info":{
									"goodsName":"OFF-WHITE 印花T恤",
									"goodsPrice":"48.80",
									"goodsDetail":""
								}
							},
							{
								"url":"../img/list-5.jpg",
								"info":{
									"goodsName":"小马可爱树脂摆件设客厅居家装饰品北欧风格创意工艺品桌面礼物品",
									"goodsPrice":"27.30",
									"goodsDetail":""
								}
							}
						],
					},
				],};